### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by SWHL** [Jumpst3r/printed-hw-segmentation#3]
Thank you for your work! It's very nice. 

I am very interested in the work, and want to reproduce the result. 

But there is a problem that I can't obtain the related dataset.

 Can you share some related links aoout the dataset? 

Thank you.

**Comment by Jumpst3r** [comment]
Thank you for your interest. We combined and modified several datasets (iamdb, rimes and marg) and complemented those with data which we generated ourselves. Unfortunately, due to restrictive end user argeements of some datasets used, we cannot share our modified version at the present time.
