### ISSUE TITLE
there is no algorithm on the web service demo

### ISSUE THREAD

**Issue by vraivon** [Jumpst3r/printed-hw-segmentation#4]
there are no algorithms available on the website.

**Comment by Jumpst3r** [comment]
I have updated the [link](http://wuersch.pillo-srv.ch/#/algorithm/5ff5b809fad531d7dc0f29c4)

**Comment by vraivon** [comment]
> I have updated the [link](http://wuersch.pillo-srv.ch/#/algorithm/5ff5b809fad531d7dc0f29c4)

thank you so much. but when testing the printed handwritten segmentation,  i got "post request for undefined failed" after processing for hundreds of seconds.
