### ISSUE TITLE
Problem of  running results

### ISSUE THREAD

**Issue by bxxk2021** [Jumpst3r/printed-hw-segmentation#7]
Hello, thank you for your work，This project looks very good. I installed the total project on ubuntu . run classifier_fcnn.py with your model file . The results did not meet expectations.What's wrong？ Can you help me ? Looking forward to your reply .thanx .The following are the images .the first is input image .The last run with --enableCRF
![input](https://user-images.githubusercontent.com/94945526/144572694-d827de2a-c346-49cf-9262-9096ffb7d2a8.png)
![fcn_out3](https://user-images.githubusercontent.com/94945526/144572784-2ee742fb-49e9-4939-8de1-7c2f1b2a3b1e.png)

![fcn_out_crf3](https://user-images.githubusercontent.com/94945526/144572820-255bb16b-2ac4-42c7-901f-d93b236ddeab.png)
)

**Comment by Jumpst3r** [comment]
Hi can you try running them with through the docker image ?
